package me.ShermansWorld.AlathraWeapons.commands;

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class WeaponsTabCompletion implements TabCompleter {
    public List<String> onTabComplete(CommandSender sender, Command cmd, String label, String[] args) {
        List<String> completions = new ArrayList<String>();
        if (args.length == 1) {
            completions.add("Katana");
            completions.add("Legendary_Katana");
            completions.add("Iron_Spear");
            completions.add("Iron_Flanged_Mace");
            completions.add("Iron_Naginata");
            completions.add("Iron_Pike");
            completions.add("Iron_Dagger");
            completions.add("Iron_Morningstar");
            completions.add("Iron_Zweihander");
            completions.add("Iron_Warhammer");
            completions.add("Iron_Shortsword");
            completions.add("Iron_Quarterstaff");
            completions.add("Iron_Kunai");
            completions.add("Iron_Sabre");
            completions.add("Iron_Halberd");
            completions.add("Iron_Combat_Axe");
            completions.add("Iron_Battleaxe");
            completions.add("Iron_Hatchet");
            completions.add("Iron_Battle_Hoe");
            completions.add("Netherite_Spear");
            completions.add("Netherite_Flanged_Mace");
            completions.add("Netherite_Naginata");
            completions.add("Netherite_Pike");
            completions.add("Netherite_Dagger");
            completions.add("Netherite_Morningstar");
            completions.add("Netherite_Zweihander");
            completions.add("Netherite_Warhammer");
            completions.add("Netherite_Shortsword");
            completions.add("Netherite_Quarterstaff");
            completions.add("Netherite_Kunai");
            completions.add("Netherite_Sabre");
            completions.add("Netherite_Halberd");
            completions.add("Netherite_Combat_Axe");
            completions.add("Netherite_Battleaxe");
            completions.add("Netherite_Hatchet");
            completions.add("Netherite_Battle_Hoe");
            completions.add("Iron_Scimitar");
            completions.add("Netherite_Scimitar");
            completions.add("Iron_Rapier");
            completions.add("Netherite_Rapier");
            completions.add("Iron_Scythe");
            completions.add("Netherite_Scythe");
            completions.add("Majestic_Katana");
            completions.add("Diamond_Spear");
            completions.add("Diamond_Naginata");
            completions.add("Diamond_Pike");
            completions.add("Diamond_Dagger");
            completions.add("Diamond_Zweihander");
            completions.add("Diamond_Shortsword");
            completions.add("Diamond_Quarterstaff");
            completions.add("Diamond_Kunai");
            completions.add("Diamond_Sabre");
            completions.add("Diamond_Twin_Blade");
            completions.add("Diamond_Scimitar");
            completions.add("Diamond_Rapier");
            completions.add("Diamond_Flanged_Mace");
            completions.add("Diamond_Morningstar");
            completions.add("Diamond_Warhammer");
            completions.add("Diamond_Hatchet");
            completions.add("Diamond_Battleaxe");
            completions.add("Diamond_Combat_Axe");
            completions.add("Diamond_Halberd");
            completions.add("Diamond_Battle_Hoe");
            completions.add("Diamond_Scythe");
            completions.add("Iron_Hook");
            completions.add("Diamond_Hook");
            completions.add("Netherite_Hook");
            completions.add("Iron_Mace");
            completions.add("Diamond_Mace");
            completions.add("Netherite_Mace");
            completions.add("Iron_Greatsword");
            completions.add("Diamond_Greatsword");
            completions.add("Netherite_Greatsword");
            completions.add("Iron_Bident");
            completions.add("Diamond_Bident");
            completions.add("Netherite_Bident");
            completions.add("Diamond_Giant_Sword");
            completions.add("Iron_Dane_Axe");
            completions.add("Diamond_Dane_Axe");
            completions.add("Netherite_Dane_Axe");
            completions.add("Iron_Antler_Staff");
            completions.add("Diamond_Antler_Staff");
            completions.add("Netherite_Antler_Staff");
            completions.add("Faebow");
            completions.add("Longbow");
            completions.add("Iron_Gladius");
            completions.add("Diamond_Gladius");
            completions.add("Netherite_Gladius");
            completions.add("Diamond_Blackfeld_Sword");
            completions.add("Netherite_Blackfeld_Sword");
            completions.add("Iron_Dreistkleze");
            completions.add("Diamond_Dreistkleze");
            completions.add("Netherite_Dreistkleze");
            completions.add("Iron_Longsword");
            completions.add("Diamond_Longsword");
            completions.add("Netherite_Longsword");
            completions.add("Iron_Giant_Sword");
            completions.add("Iron_Blackfeld_Sword");
            completions.add("Netherite_Giant_Sword");
            completions.add("Golden_Giant_Sword");
            completions.add("Glorious_Katana");
            completions.add("Golden_Spear");
            completions.add("Golden_Naginata");
            completions.add("Golden_Pike");
            completions.add("Golden_Dagger");
            completions.add("Golden_Zweihander");
            completions.add("Golden_Shortsword");
            completions.add("Golden_Quarterstaff");
            completions.add("Golden_Kunai");
            completions.add("Golden_Sabre");
            completions.add("Golden_Twin_Blade");
            completions.add("Golden_Scimitar");
            completions.add("Golden_Rapier");
            completions.add("Golden_Hook");
            completions.add("Golden_Mace");
            completions.add("Golden_Greatsword");
            completions.add("Golden_Bident");
            completions.add("Golden_Gladius");
            completions.add("Golden_Blackfeld_Sword");
            completions.add("Golden_Dreistkleze");
            completions.add("Golden_Longsword");
            completions.add("Golden_Flanged_Mace");
            completions.add("Golden_Morningstar");
            completions.add("Golden_Warhammer");
            completions.add("Golden_Hatchet");
            completions.add("Golden_Battleaxe");
            completions.add("Golden_Combat_Axe");
            completions.add("Golden_Halberd");
            completions.add("Golden_Battle_Hoe");
            completions.add("Golden_Scythe");
            completions.add("Golden_Dane_Axe");
            completions.add("Iron_Twin_Blade");
            completions.add("Netherite_Twin_Blade");
            return completions;
        }
        return Collections.emptyList();
    }
}
