package me.ShermansWorld.AlathraWeapons;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;

public class WeaponsTabCompletion implements TabCompleter {
	public List<String> onTabComplete(CommandSender sender, Command cmd, String label, String[] args) {
		List<String> completions = new ArrayList<String>();
		if (args.length == 1) {
			completions.add("Katana");
			completions.add("Legendary_Katana");
			completions.add("Iron_Spear");
			completions.add("Iron_Flanged_Mace");
			completions.add("Iron_Naginata");
			completions.add("Iron_Pike");
			completions.add("Iron_Dagger");
			completions.add("Iron_Morning_Star");
			completions.add("Iron_Zweihander");
			completions.add("Iron_Warhammer");
			completions.add("Iron_Shortsword");
			completions.add("Iron_Quarterstaff");
			completions.add("Iron_Kunai");
			completions.add("Iron_Sabre");
			completions.add("Iron_Halberd");
			completions.add("Iron_Combat_Axe");
			completions.add("Iron_Battleaxe");
			completions.add("Iron_Hatchet");
			completions.add("Iron_Battle_Hoe");
			completions.add("Netherite_Spear");
			completions.add("Netherite_Flanged_Mace");
			completions.add("Netherite_Naginata");
			completions.add("Netherite_Pike");
			completions.add("Netherite_Dagger");
			completions.add("Netherite_Morning_Star");
			completions.add("Netherite_Zweihander");
			completions.add("Netherite_Warhammer");
			completions.add("Netherite_Shortsword");
			completions.add("Netherite_Quarterstaff");
			completions.add("Netherite_Kunai");
			completions.add("Netherite_Sabre");
			completions.add("Netherite_Halberd");
			completions.add("Netherite_Combat_Axe");
			completions.add("Netherite_Battleaxe");
			completions.add("Netherite_Hatchet");
			completions.add("Netherite_Battle_Hoe");
			completions.add("Iron_Scimitar");
			completions.add("Netherite_Scimitar");
			completions.add("Iron_Rapier");
			completions.add("Netherite_Rapier");
			completions.add("Iron_Scythe");
			completions.add("Netherite_Scythe");
			completions.add("Diamond_Katana");
			completions.add("Diamond_Spear");
			completions.add("Diamond_Naginata");
			completions.add("Diamond_Pike");
			completions.add("Diamond_Dagger");
			completions.add("Diamond_Zweihander");
			completions.add("Diamond_Shortsword");
			completions.add("Diamond_Quarterstaff");
			completions.add("Diamond_Kunai");
			completions.add("Diamond_Sabre");
			completions.add("Diamond_Twin_Blade");
			completions.add("Diamond_Scimitar");
			completions.add("Diamond_Rapier");
			completions.add("Diamond_Flanged_Mace");
			completions.add("Diamond_Morning_Star");
			completions.add("Diamond_Warhammer");
			completions.add("Diamond_Hatchet");
			completions.add("Diamond_Battleaxe");
			completions.add("Diamond_Combat_Axe");
			completions.add("Diamond_Halberd");
			completions.add("Diamond_Battle_Hoe");
			completions.add("Diamond_Scythe");
			completions.add("Iron_Hook");
			completions.add("Diamond_Hook");
			completions.add("Netherite_Hook");
			completions.add("Iron_Mace");
			completions.add("Diamond_Mace");
			completions.add("Netherite_Mace");
			completions.add("Iron_Greatsword");
			completions.add("Diamond_Greatsword");
			completions.add("Netherite_Greatsword");
			completions.add("Iron_Bident");
			completions.add("Diamond_Bident");
			completions.add("Netherite_Bident");
			completions.add("Diamond_Giant_Sword");
			completions.add("Iron_Dane_Axe");
			completions.add("Diamond_Dane_Axe");
			completions.add("Netherite_Dane_Axe");
			completions.add("Iron_Antler_Staff");
			completions.add("Diamond_Antler_Staff");
			completions.add("Netherite_Antler_Staff");
			completions.add("Faebow");
			return completions;
		}
		return Collections.emptyList();
	}
}
